### ISSUE TITLE
some numbers aren't numbers

### ISSUE THREAD

**Issue by denjell-crabnebula** [coplat/rng#1]
I tried entering the following, but it gave errors.

- [ ] negative number (-123)
- [ ] huge number (1000000000000000)
- [ ] decimals

<details><summary>Click here for a hint</summary>
<p>
There's a singular type that would solve for all three cases.
</p>
</details> 

<details><summary>Click here for the answer</summary>
<p>
f64
</p>
</details> 

This is a reason why you probably want to also write tests.

**Comment by denjell-crabnebula** [comment]
<img width="527" alt="image" src="https://github.com/user-attachments/assets/0462710e-0c4e-489c-8aa7-674dea8c49c9">

**Comment by coplat** [comment]
gotcha. 
changed type, think i prefer the random number output being rounded though - so have added that in. works well for me so far.
